### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by useo6** [Coac/cryptopia.js#2]
The package isn't working for me anymore since yesterday. It always tells me "UNABLE_TO_VERIFY_LEAF_SIGNATURE" / "Unable to verify the first certificate". I think it's necessary to add a parameter to the Cryptopia-constructor to set Cryptopia's crt file for https connections.

**Comment by Coac** [comment]
I just tested on public endpoints and some private, it's working well for me.  I cannot reproduce your error.
What endpoint did you use to get this error ?

**Comment by useo6** [comment]
I finally figured out that it was necessary to install the cryptopia crt-files using the 'ssl-root-cas' package. This solved the problem...

**Comment by Coac** [comment]
Good to hear you solved it 😃
